# Generated by Django 4.2.7 on 2026-01-01 03:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUALIFIED", "Qualified"),
                            ("BONUS_AWARDED", "Bonus Awarded"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the referral",
                        max_length=20,
                    ),
                ),
                (
                    "referrer_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Bonus amount for referrer",
                        max_digits=10,
                    ),
                ),
                (
                    "referred_user_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Bonus amount for referred user",
                        max_digits=10,
                    ),
                ),
                (
                    "bonus_awarded_at",
                    models.DateTimeField(
                        blank=True, help_text="When bonus was awarded", null=True
                    ),
                ),
                (
                    "referred_user_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total deposit amount by referred user",
                        max_digits=10,
                    ),
                ),
                (
                    "deposit_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date when deposit requirement was met",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if status is REJECTED",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the referral bonus expires if not qualified"
                    ),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        help_text="User who was referred",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        help_text="User who made the referral",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("PAUSED", "Paused"),
                        ],
                        default="ACTIVE",
                        help_text="Enable/disable the entire referral program",
                        max_length=20,
                    ),
                ),
                (
                    "referral_bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Bonus amount credited to referrer when new user registers",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "referred_user_bonus",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        help_text="Bonus amount credited to newly referred user",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "minimum_referral_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Minimum deposit required by referred user to qualify for bonus",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "bonus_expiry_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days before unclaimed bonus expires",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "min_referral_balance_to_withdraw",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Minimum referral bonus balance required to initiate withdrawal",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_withdrawals_per_month",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Maximum number of referral bonus withdrawals per user per month",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referral Program",
                "verbose_name_plural": "Referral Program",
            },
        ),
        migrations.CreateModel(
            name="ReferralWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount to withdraw",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Withdrawal status",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Payment method (bank, wallet, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notes from admin"),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for rejection if status is REJECTED",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When withdrawal was processed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who processed this withdrawal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_referral_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User requesting withdrawal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Withdrawal",
                "verbose_name_plural": "Referral Withdrawals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="referrals_r_user_id_955375_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="referrals_r_created_9a94b4_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code for referral link",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "total_referred",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of successful referrals"
                    ),
                ),
                (
                    "total_bonus_earned",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total bonus earned from all referrals",
                        max_digits=15,
                    ),
                ),
                (
                    "total_referrals_clicked",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of clicks on referral link"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_link",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Link",
                "verbose_name_plural": "Referral Links",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="referrals_r_user_id_bf137d_idx",
                    ),
                    models.Index(
                        fields=["referral_code"], name="referrals_r_referra_e479e5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferralBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("REFERRER", "Referrer Bonus"),
                            ("REFERRED", "Referred User Bonus"),
                        ],
                        help_text="Type of bonus",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bonus amount",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CREDITED", "Credited"),
                            ("EXPIRED", "Expired"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="PENDING",
                        help_text="Bonus status",
                        max_length=20,
                    ),
                ),
                (
                    "credited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When bonus was credited to wallet",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "referral",
                    models.ForeignKey(
                        help_text="Referral that triggered this bonus",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonuses",
                        to="referrals.referral",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who received the bonus",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_bonuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Bonus",
                "verbose_name_plural": "Referral Bonuses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="referrals_r_user_id_fe28c2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="referrals_r_created_045edb_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referrals_r_referre_ebbb80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referred_user", "status"],
                name="referrals_r_referre_cf1f1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["created_at"], name="referrals_r_created_81091c_idx"
            ),
        ),
    ]
