# Generated by Django 4.2.7 on 2026-02-13 01:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotsGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paytable', models.JSONField(default=dict, help_text='Symbol -> multiplier for 3 matching')),
                ('reels', models.JSONField(default=list, help_text='List of 3 reels, each with symbols')),
                ('rtp_percent', models.DecimalField(decimal_places=2, default=96.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_bet', models.DecimalField(decimal_places=2, default=0.1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('max_bet', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_slots_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slots_games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotsSpin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('symbols', models.JSONField(default=list)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('random_seed', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spins', to='slots.slotsgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slots_spins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='slots_spins_user_id_f9c95f_idx'), models.Index(fields=['game', '-created_at'], name='slots_spins_game_id_e41006_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='slotsgame',
            index=models.Index(fields=['is_active'], name='slots_games_is_acti_e38985_idx'),
        ),
    ]
