# Generated by Django 4.2.7 on 2026-01-21 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TICKET_PURCHASED', 'Ticket Purchased'), ('DRAW_RESULT', 'Draw Result'), ('WINNER', 'Winner'), ('WITHDRAWAL_STATUS', 'Withdrawal Status'), ('REFERRAL_BONUS', 'Referral Bonus'), ('LOTTERY_ENDING_SOON', 'Lottery Ending Soon'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate when notification is clicked')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_d2e2f1_idx')],
            },
        ),
    ]
