# Generated by Django 4.2.7 on 2026-01-06 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_email_verification_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(
                blank=True, default=dict, help_text="Before/after values for the change"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(
                blank=True,
                help_text="UUID or ID of the affected resource",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="resource_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USER", "User"),
                    ("LOTTERY", "Lottery"),
                    ("TRANSACTION", "Transaction"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("REFERRAL", "Referral"),
                    ("PAYMENT", "Payment"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_proof",
            field=models.FileField(blank=True, null=True, upload_to="kyc/address/"),
        ),
        migrations.AddField(
            model_name="user",
            name="age_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="age_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_deposit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="daily_loss_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="kyc/id/"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(
                default=False, help_text="Whether 2FA is enabled for this user"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PENDING", "Pending"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="kyc_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_session_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_deposit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="self_excluded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="self_exclusion_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="session_time_limit",
            field=models.IntegerField(
                blank=True, help_text="Session time limit in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="Backup codes for 2FA"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, help_text="TOTP secret key", max_length=32, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_deposit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_referral_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total earnings from referrals",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_referrals",
            field=models.IntegerField(
                default=0, help_text="Total number of successful referrals"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="audit_logs_resourc_bda8a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["wallet_balance"], name="users_wallet__466abd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="users_role_a8f2ba_idx"
            ),
        ),
    ]
