# Generated by Django 4.2.7 on 2026-01-01 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lottery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tickets", models.IntegerField()),
                ("available_tickets", models.IntegerField()),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("DRAWN", "Drawn"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("draw_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_lotteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lotteries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ticket_number", models.IntegerField()),
                ("is_winner", models.BooleanField(default=False)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_set",
                        to="lotteries.lottery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="LotteryDrawLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_participants", models.IntegerField()),
                ("total_tickets_sold", models.IntegerField()),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=10)),
                ("random_seed", models.CharField(max_length=255)),
                ("drawn_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lottery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draw_log",
                        to="lotteries.lottery",
                    ),
                ),
            ],
            options={
                "db_table": "lottery_draw_logs",
                "ordering": ["-drawn_at"],
            },
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("announced_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("is_claimed", models.BooleanField(default=False)),
                (
                    "lottery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winners",
                        to="lotteries.lottery",
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner",
                        to="lotteries.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "winners",
                "ordering": ["-announced_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-announced_at"],
                        name="winners_user_id_43b024_idx",
                    ),
                    models.Index(fields=["lottery"], name="winners_lottery_eb2096_idx"),
                    models.Index(
                        fields=["is_claimed"], name="winners_is_clai_46eede_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["user", "lottery"], name="tickets_user_id_d6a44b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["lottery", "is_winner"], name="tickets_lottery_dc77f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["-purchased_at"], name="tickets_purchas_c3498f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("lottery", "ticket_number")},
        ),
        migrations.AddIndex(
            model_name="lottery",
            index=models.Index(fields=["status"], name="lotteries_status_92b012_idx"),
        ),
        migrations.AddIndex(
            model_name="lottery",
            index=models.Index(
                fields=["draw_date"], name="lotteries_draw_da_097926_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lottery",
            index=models.Index(
                fields=["-created_at"], name="lotteries_created_1c20c4_idx"
            ),
        ),
    ]
