# Generated by Django 4.2.7 on 2026-01-06 01:47

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("lotteries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LotteryTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("ticket_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_tickets", models.IntegerField()),
                ("prize_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_tickets_per_user",
                    models.PositiveIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("America/New_York", "Eastern Time (US & Canada)"),
                            ("America/Chicago", "Central Time (US & Canada)"),
                            ("America/Denver", "Mountain Time (US & Canada)"),
                            ("America/Los_Angeles", "Pacific Time (US & Canada)"),
                            ("Europe/London", "London"),
                            ("Europe/Paris", "Paris"),
                            ("Europe/Berlin", "Berlin"),
                            ("Asia/Dubai", "Dubai"),
                            ("Asia/Kolkata", "India"),
                            ("Asia/Singapore", "Singapore"),
                            ("Asia/Tokyo", "Tokyo"),
                            ("Australia/Sydney", "Sydney"),
                        ],
                        default="UTC",
                        max_length=50,
                    ),
                ),
                ("auto_draw", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is available for use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lottery_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lottery",
            name="auto_draw",
            field=models.BooleanField(
                default=False,
                help_text="Automatically conduct draw when end_date is reached",
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="end_date",
            field=models.DateTimeField(
                blank=True, help_text="When ticket sales end", null=True
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Feature this lottery on homepage"
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="max_tickets_per_user",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum tickets a single user can purchase",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="start_date",
            field=models.DateTimeField(
                blank=True, help_text="When ticket sales start", null=True
            ),
        ),
        migrations.AddField(
            model_name="lottery",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("UTC", "UTC"),
                    ("America/New_York", "Eastern Time (US & Canada)"),
                    ("America/Chicago", "Central Time (US & Canada)"),
                    ("America/Denver", "Mountain Time (US & Canada)"),
                    ("America/Los_Angeles", "Pacific Time (US & Canada)"),
                    ("Europe/London", "London"),
                    ("Europe/Paris", "Paris"),
                    ("Europe/Berlin", "Berlin"),
                    ("Asia/Dubai", "Dubai"),
                    ("Asia/Kolkata", "India"),
                    ("Asia/Singapore", "Singapore"),
                    ("Asia/Tokyo", "Tokyo"),
                    ("Australia/Sydney", "Sydney"),
                ],
                default="UTC",
                help_text="Timezone for lottery dates",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="lottery",
            index=models.Index(
                fields=["status", "draw_date"], name="lotteries_status_fc91e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lottery",
            index=models.Index(
                fields=["featured", "-created_at"], name="lotteries_feature_857277_idx"
            ),
        ),
    ]
