# Generated by Django 4.2.7 on 2026-01-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("TICKET_PURCHASE", "Ticket Purchase"),
                    ("PRIZE_AWARD", "Prize Award"),
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("REFUND", "Refund"),
                    ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                    ("REFERRAL_BONUS", "Referral Bonus"),
                ],
                max_length=50,
            ),
        ),
    ]
