# Generated by Django 4.2.7 on 2026-02-26 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='game_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='games.gameroom'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TICKET_PURCHASE', 'Ticket Purchase'), ('PRIZE_AWARD', 'Prize Award'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('REFERRAL_BONUS', 'Referral Bonus'), ('SLOTS_BET', 'Slots Bet'), ('SLOTS_WIN', 'Slots Win'), ('GAME_ENTRY', 'Game Entry'), ('GAME_WIN', 'Game Win'), ('GAME_REFUND', 'Game Refund')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['game_room'], name='transaction_game_ro_3af1f3_idx'),
        ),
    ]
