# Generated by Django 4.2.7 on 2026-02-26 00:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_kind', models.CharField(choices=[('SNAKES_LADDERS', 'Snakes & Ladders'), ('LUDO', 'Ludo'), ('CARROM', 'Carrom')], max_length=32)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('min_players', models.PositiveSmallIntegerField(default=2)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_game_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_state', to='games.gameroom')),
            ],
            options={
                'db_table': 'games_state',
            },
        ),
        migrations.CreateModel(
            name='GameRoomPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('balance_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result', models.CharField(blank=True, choices=[('WON', 'Won'), ('LOST', 'Lost'), ('DRAW', 'Draw'), ('DISCONNECTED', 'Disconnected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gameroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_room_players', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_room_players',
                'ordering': ['room', 'position'],
                'indexes': [models.Index(fields=['room'], name='games_room__room_id_87cbe4_idx'), models.Index(fields=['user'], name='games_room__user_id_92d7ea_idx')],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['game_kind'], name='games_rooms_game_ki_8f445f_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['status'], name='games_rooms_status_8c3fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='gameroom',
            index=models.Index(fields=['-created_at'], name='games_rooms_created_adba8f_idx'),
        ),
    ]
