# Generated by Django 4.2.7 on 2026-01-06 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payment_int_user_id_01c2fa_idx",
            old_name="payment_int_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payment_int_status_0f02ee_idx",
            old_name="payment_int_status_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payment_int_stripe__443f7f_idx",
            old_name="payment_int_stripe_idx",
        ),
    ]
